/*******************************************************************************
 * Copyright 2012, Oracle Corporation and/or its affiliates. All rights reserved. Title, ownership
 * rights, and intellectual property rights in and to this software remain with Oracle Corporation.
 * Oracle Corporation hereby reserves all rights in and to this software. This software may not be
 * copied, modified, or used without a license from Oracle Corporation. This software is protected
 * by international copyright laws and treaties, and may be protected by other laws. Violation of
 * copyright laws may result in civil liability and criminal penalties.
 ******************************************************************************/

package oracle.apps.hcm.hwr.ws.client;

import com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;
import com.oracle.xmlns.apps.hcm.hwr.coreservice.WorkforceReputationService;


/**
 * Interface to define the different types of data we can send to the server.
 * 
 * @author tgsnyder
 *
 */
public interface ISendServerMsg {

    /**
     * Interface to the auto-generated client code to make a request from the server.  
     * Used to define the different entry points from the client to the server.
     * 
     * @param pWorkforceReputationPublicService - The initialized WorkforceReputationPublicService.
     *     From the autogenerated code.
     * @param pMsgToSend - Message to send to the server.
     * @return - The result from the server.
     * @throws ServiceException
     */
    public String sendServerMsg(WorkforceReputationService pWorkforceReputationPublicService, 
        String pMsgToSend) throws ServiceException;
    
    /**
     * 
     * @return: The name of the method (in the server side) that was invoked. Useful for logging purposes.
     */
    public String getMethodName();
}
