package oracle.apps.hcm.hwr.ws.client.email.autogen;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

//@WebService(wsdlLocation="http://slc01qmf.us.oracle.com:7022/soa-infra/services/default/Bpel_Email_Notification/bpelemailnotification_client_ep?WSDL",
//  targetNamespace="http://xmlns.oracle.com/Bpel_Email_Notification/Bpel_Email_Notification/BpelEmailNotification",
//  name="BpelEmailNotification")
@WebService
@XmlSeeAlso(
  { oracle.apps.hcm.hwr.ws.client.email.autogen.ObjectFactory.class })
public interface BpelEmailNotification
{
  @WebMethod(action="process")
  @Action(input="process")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/Bpel_Email_Notification/Bpel_Email_Notification/BpelEmailNotification",
    className="oracle.apps.hcm.hwr.ws.client.email.autogen.Process")
  @Oneway
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/Bpel_Email_Notification/Bpel_Email_Notification/BpelEmailNotification",
      name="Email-ID")
    String emailID, @WebParam(targetNamespace="http://xmlns.oracle.com/Bpel_Email_Notification/Bpel_Email_Notification/BpelEmailNotification",
      name="Subject")
    String subject, @WebParam(targetNamespace="http://xmlns.oracle.com/Bpel_Email_Notification/Bpel_Email_Notification/BpelEmailNotification",
      name="Body")
    String body);
}
