package oracle.apps.hcm.hwr.ws.client.email.autogen;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

//@WebServiceClient(wsdlLocation="http://slc01qmf.us.oracle.com:7022/soa-infra/services/default/Bpel_Email_Notification/bpelemailnotification_client_ep?WSDL",
//  targetNamespace="http://xmlns.oracle.com/Bpel_Email_Notification/Bpel_Email_Notification/BpelEmailNotification",
//  name="bpelemailnotification_client_ep")
@WebServiceClient
public class Bpelemailnotification_client_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  /*
  static
  {
    try
    {
      logger = Logger.getLogger("oracle.apps.hcm.hwr.ws.client.email.autogen.Bpelemailnotification_client_ep");
      URL baseUrl = Bpelemailnotification_client_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Bpelemailnotification_client_ep.class.getResource("http://slc01qmf.us.oracle.com:7022/soa-infra/services/default/Bpel_Email_Notification/bpelemailnotification_client_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://slc01qmf.us.oracle.com:7022/soa-infra/services/default/Bpel_Email_Notification/bpelemailnotification_client_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://slc01qmf.us.oracle.com:7022/soa-infra/services/default/Bpel_Email_Notification/bpelemailnotification_client_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://slc01qmf.us.oracle.com:7022/soa-infra/services/default/Bpel_Email_Notification/bpelemailnotification_client_ep?WSDL",
          e);
    }
  }
*/

  public Bpelemailnotification_client_ep(String pWsdlURL)
  {
    super(createWsdlLocationURL(pWsdlURL),
          new QName("http://xmlns.oracle.com/Bpel_Email_Notification/Bpel_Email_Notification/BpelEmailNotification",
                    "bpelemailnotification_client_ep"));
  }

  public static URL createWsdlLocationURL(String pWsdlURL) {
      try
      {
        logger = Logger.getLogger("oracle.apps.hcm.hwr.ws.client.email.autogen.Bpelemailnotification_client_ep");
        URL baseUrl = Bpelemailnotification_client_ep.class.getResource(".");
        if (baseUrl == null)
        {
          wsdlLocationURL =
              Bpelemailnotification_client_ep.class.getResource(pWsdlURL);
          if (wsdlLocationURL == null)
          {
            baseUrl = new File(".").toURL();
            wsdlLocationURL =
                new URL(baseUrl, pWsdlURL);
          }
        }
        else
        {
                  if (!baseUrl.getPath().endsWith("/")) {
           baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
      }
                  wsdlLocationURL =
              new URL(baseUrl, pWsdlURL);
        }
      }
      catch (MalformedURLException e)
      {
        logger.log(Level.ALL,
            "Failed to create wsdlLocationURL using " + pWsdlURL,
            e);
      }

      return wsdlLocationURL;
  }

  public Bpelemailnotification_client_ep(URL wsdlLocation,
                                         QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="BpelEmailNotification_pt")
  public oracle.apps.hcm.hwr.ws.client.email.autogen.BpelEmailNotification getBpelEmailNotification_pt()
  {
    return (oracle.apps.hcm.hwr.ws.client.email.autogen.BpelEmailNotification) super.getPort(new QName("http://xmlns.oracle.com/Bpel_Email_Notification/Bpel_Email_Notification/BpelEmailNotification",
                                                                                                       "BpelEmailNotification_pt"),
                                                                                             oracle.apps.hcm.hwr.ws.client.email.autogen.BpelEmailNotification.class);
  }

  @WebEndpoint(name="BpelEmailNotification_pt")
  public oracle.apps.hcm.hwr.ws.client.email.autogen.BpelEmailNotification getBpelEmailNotification_pt(WebServiceFeature... features)
  {
    return (oracle.apps.hcm.hwr.ws.client.email.autogen.BpelEmailNotification) super.getPort(new QName("http://xmlns.oracle.com/Bpel_Email_Notification/Bpel_Email_Notification/BpelEmailNotification",
                                                                                                       "BpelEmailNotification_pt"),
                                                                                             oracle.apps.hcm.hwr.ws.client.email.autogen.BpelEmailNotification.class,
                                                                                             features);
  }
}
