package oracle.apps.hcm.hwr.coreService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
import oracle.webservices.annotations.async.AsyncWebService;
import oracle.webservices.annotations.async.CallbackMethod;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 04 14:05:44 PST 2012
// ---------------------------------------------------------------------
@AsyncWebService
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/",
  name="WorkforceReputationService", wsdlLocation="oracle/apps/hcm/hwr/coreService/WorkforceReputationService.wsdl")
@SDODatabinding(schemaLocation="oracle/apps/hcm/hwr/coreService/WorkforceReputationService.xsd")
public interface WorkforceReputationService {


  public static final String NAME = "{http://xmlns.oracle.com/apps/hcm/hwr/coreService/}WorkforceReputationService";

  /**
   * Exported method pollForJob from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/pollForJob",
    operationName="pollForJob")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="pollForJob")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="pollForJobResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String pollForJob(@WebParam(mode = WebParam.Mode.IN, name="WLA")
    String WLA) throws ServiceException;

    /**
   * Exported method updateJobProgress from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/updateJobProgress",
    operationName="updateJobProgress")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="updateJobProgress")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="updateJobProgressResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String updateJobProgress(@WebParam(mode = WebParam.Mode.IN, name="JobId")
    String JobId) throws ServiceException;

    /**
   * Exported method writeConnectorData from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/writeConnectorData",
    operationName="writeConnectorData")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="writeConnectorData")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="writeConnectorDataResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String writeConnectorData(@WebParam(mode = WebParam.Mode.IN, name="DataWriter")
    String DataWriter) throws ServiceException;

    /**
   * Exported method mergePersonaSyncData from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/mergePersonaSyncData",
    operationName="mergePersonaSyncData")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="mergePersonaSyncData")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="mergePersonaSyncDataResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String mergePersonaSyncData(@WebParam(mode = WebParam.Mode.IN, name="PersonaSyncdata")
    String PersonaSyncdata) throws ServiceException;

    /**
   * Exported method registerUser from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/registerUser",
    operationName="registerUser")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="registerUser")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="registerUserResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String registerUser(@WebParam(mode = WebParam.Mode.IN, name="PersonaSyncdata")
    String PersonaSyncdata) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/mergePersonaSyncDataAsync",
    operationName="mergePersonaSyncDataAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="mergePersonaSyncDataAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="mergePersonaSyncDataAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/mergePersonaSyncDataAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/mergePersonaSyncDataAsyncResponse")
  String mergePersonaSyncDataAsync(@WebParam(mode = WebParam.Mode.IN, name="PersonaSyncdata")
    String PersonaSyncdata) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/updateJobProgressAsync",
    operationName="updateJobProgressAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="updateJobProgressAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="updateJobProgressAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/updateJobProgressAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/updateJobProgressAsyncResponse")
  String updateJobProgressAsync(@WebParam(mode = WebParam.Mode.IN, name="JobId")
    String JobId) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/pollForJobAsync",
    operationName="pollForJobAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="pollForJobAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="pollForJobAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/pollForJobAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/pollForJobAsyncResponse")
  String pollForJobAsync(@WebParam(mode = WebParam.Mode.IN, name="WLA")
    String WLA) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/writeConnectorDataAsync",
    operationName="writeConnectorDataAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="writeConnectorDataAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="writeConnectorDataAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/writeConnectorDataAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/writeConnectorDataAsyncResponse")
  String writeConnectorDataAsync(@WebParam(mode = WebParam.Mode.IN, name="DataWriter")
    String DataWriter) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/registerUserAsync",
    operationName="registerUserAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="registerUserAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="registerUserAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/registerUserAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/registerUserAsyncResponse")
  String registerUserAsync(@WebParam(mode = WebParam.Mode.IN, name="PersonaSyncdata")
    String PersonaSyncdata) throws ServiceException;

    /**
   * Exported method initializeWLA from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/initializeWLA",
    operationName="initializeWLA")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="initializeWLA")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="initializeWLAResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String initializeWLA(@WebParam(mode = WebParam.Mode.IN, name="initializationInformation")
    String initializationInformation) throws ServiceException;

    /**
   * Exported method getUserProfile from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserProfile",
    operationName="getUserProfile")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getUserProfile")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getUserProfileResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String getUserProfile(@WebParam(mode = WebParam.Mode.IN, name="profileInformation")
    String profileInformation) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/initializeWLAAsync",
    operationName="initializeWLAAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="initializeWLAAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="initializeWLAAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/initializeWLAAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/initializeWLAAsyncResponse")
  String initializeWLAAsync(@WebParam(mode = WebParam.Mode.IN, name="initializationInformation")
    String initializationInformation) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserProfileAsync",
    operationName="getUserProfileAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getUserProfileAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getUserProfileAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserProfileAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserProfileAsyncResponse")
  String getUserProfileAsync(@WebParam(mode = WebParam.Mode.IN, name="profileInformation")
    String profileInformation) throws ServiceException;

  /**
   * Exported method getMyEndorsements from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getMyEndorsements",
    operationName="getMyEndorsements")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getMyEndorsements")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getMyEndorsementsResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String getMyEndorsements(@WebParam(mode = WebParam.Mode.IN, name="pGlobalProfileId")
    String pGlobalProfileId) throws ServiceException;

  /**
   * Exported method getUserToEndorse from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserToEndorse",
    operationName="getUserToEndorse")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getUserToEndorse")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getUserToEndorseResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String getUserToEndorse(@WebParam(mode = WebParam.Mode.IN, name="pGlobalProfileIds")
    String pGlobalProfileIds) throws ServiceException;

  /**
   * Exported method searchUserToEndorse from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/searchUserToEndorse",
    operationName="searchUserToEndorse")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="searchUserToEndorse")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="searchUserToEndorseResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String searchUserToEndorse(@WebParam(mode = WebParam.Mode.IN, name="pSearchCriteria")
    String pSearchCriteria) throws ServiceException;

  /**
   * Exported method EndorseUser from WorkforceReputationPublicServiceAM.
   */
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/EndorseUser",
    operationName="EndorseUser")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="EndorseUser")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="EndorseUserResponse")
  @WebResult(name="result")
  @CallbackMethod(exclude=true)
  String EndorseUser(@WebParam(mode = WebParam.Mode.IN, name="pEndorsement")
    String pEndorsement) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/searchUserToEndorseAsync",
    operationName="searchUserToEndorseAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="searchUserToEndorseAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="searchUserToEndorseAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/searchUserToEndorseAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/searchUserToEndorseAsyncResponse")
  String searchUserToEndorseAsync(@WebParam(mode = WebParam.Mode.IN, name="pSearchCriteria")
    String pSearchCriteria) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/EndorseUserAsync",
    operationName="EndorseUserAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="EndorseUserAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="EndorseUserAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/EndorseUserAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/EndorseUserAsyncResponse")
  String EndorseUserAsync(@WebParam(mode = WebParam.Mode.IN, name="pEndorsement")
    String pEndorsement) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserToEndorseAsync",
    operationName="getUserToEndorseAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getUserToEndorseAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getUserToEndorseAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserToEndorseAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserToEndorseAsyncResponse")
  String getUserToEndorseAsync(@WebParam(mode = WebParam.Mode.IN, name="pGlobalProfileIds")
    String pGlobalProfileIds) throws ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getMyEndorsementsAsync",
    operationName="getMyEndorsementsAsync")
  @RequestWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getMyEndorsementsAsync")
  @ResponseWrapper(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    localName="getMyEndorsementsAsyncResponse")
  @WebResult(name="result")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getMyEndorsementsAsync",
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getMyEndorsementsAsyncResponse")
  String getMyEndorsementsAsync(@WebParam(mode = WebParam.Mode.IN, name="pGlobalProfileId")
    String pGlobalProfileId) throws ServiceException;
}
