package com.oracle.xmlns.apps.hcm.hwr.coreservice;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://slc06xac.us.oracle.com:7021/workforceReputationServiceCore/WorkforceReputationService?wsdl",
  targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/",
  name="WorkforceReputationService")
@XmlSeeAlso(
  { com.oracle.xmlns.apps.hcm.hwr.coreservice.types.ObjectFactory.class })
public interface WorkforceReputationService
{
  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/pollForJob")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/pollForJob", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/pollForJob/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/pollForJobResponse")
  @ResponseWrapper(localName="pollForJobResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.PollForJobResponse")
  @RequestWrapper(localName="pollForJob", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.PollForJob")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String pollForJob(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="WLA")
    String wla)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/updateJobProgress")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/updateJobProgress", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/updateJobProgress/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/updateJobProgressResponse")
  @ResponseWrapper(localName="updateJobProgressResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.UpdateJobProgressResponse")
  @RequestWrapper(localName="updateJobProgress", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.UpdateJobProgress")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String updateJobProgress(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="JobId")
    String jobId)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/writeConnectorData")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/writeConnectorData", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/writeConnectorData/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/writeConnectorDataResponse")
  @ResponseWrapper(localName="writeConnectorDataResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.WriteConnectorDataResponse")
  @RequestWrapper(localName="writeConnectorData", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.WriteConnectorData")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String writeConnectorData(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="DataWriter")
    String dataWriter)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/mergePersonaSyncData")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/mergePersonaSyncData", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/mergePersonaSyncData/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/mergePersonaSyncDataResponse")
  @ResponseWrapper(localName="mergePersonaSyncDataResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.MergePersonaSyncDataResponse")
  @RequestWrapper(localName="mergePersonaSyncData", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.MergePersonaSyncData")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String mergePersonaSyncData(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="PersonaSyncdata")
    String personaSyncdata)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/registerUser")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/registerUser", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/registerUser/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/registerUserResponse")
  @ResponseWrapper(localName="registerUserResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.RegisterUserResponse")
  @RequestWrapper(localName="registerUser", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.RegisterUser")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String registerUser(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="PersonaSyncdata")
    String personaSyncdata)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/mergePersonaSyncDataAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/mergePersonaSyncDataAsync")
  @RequestWrapper(localName="mergePersonaSyncDataAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.MergePersonaSyncDataAsync")
  @Oneway
  public void mergePersonaSyncDataAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="PersonaSyncdata")
    String personaSyncdata);

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/updateJobProgressAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/updateJobProgressAsync")
  @RequestWrapper(localName="updateJobProgressAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.UpdateJobProgressAsync")
  @Oneway
  public void updateJobProgressAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="JobId")
    String jobId);

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/pollForJobAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/pollForJobAsync")
  @RequestWrapper(localName="pollForJobAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.PollForJobAsync")
  @Oneway
  public void pollForJobAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="WLA")
    String wla);

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/writeConnectorDataAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/writeConnectorDataAsync")
  @RequestWrapper(localName="writeConnectorDataAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.WriteConnectorDataAsync")
  @Oneway
  public void writeConnectorDataAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="DataWriter")
    String dataWriter);

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/registerUserAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/registerUserAsync")
  @RequestWrapper(localName="registerUserAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.RegisterUserAsync")
  @Oneway
  public void registerUserAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="PersonaSyncdata")
    String personaSyncdata);

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/initializeWLA")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/initializeWLA", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/initializeWLA/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/initializeWLAResponse")
  @ResponseWrapper(localName="initializeWLAResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.InitializeWLAResponse")
  @RequestWrapper(localName="initializeWLA", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.InitializeWLA")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String initializeWLA(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="initializationInformation")
    String initializationInformation)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserProfile")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserProfile", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/getUserProfile/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/getUserProfileResponse")
  @ResponseWrapper(localName="getUserProfileResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.GetUserProfileResponse")
  @RequestWrapper(localName="getUserProfile", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.GetUserProfile")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String getUserProfile(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="profileInformation")
    String profileInformation)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/initializeWLAAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/initializeWLAAsync")
  @RequestWrapper(localName="initializeWLAAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.InitializeWLAAsync")
  @Oneway
  public void initializeWLAAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="initializationInformation")
    String initializationInformation);

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserProfileAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserProfileAsync")
  @RequestWrapper(localName="getUserProfileAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.GetUserProfileAsync")
  @Oneway
  public void getUserProfileAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="profileInformation")
    String profileInformation);

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getMyEndorsements")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getMyEndorsements", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/getMyEndorsements/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/getMyEndorsementsResponse")
  @ResponseWrapper(localName="getMyEndorsementsResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.GetMyEndorsementsResponse")
  @RequestWrapper(localName="getMyEndorsements", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.GetMyEndorsements")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String getMyEndorsements(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="pGlobalProfileId")
    String pGlobalProfileId)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserToEndorse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserToEndorse", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/getUserToEndorse/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/getUserToEndorseResponse")
  @ResponseWrapper(localName="getUserToEndorseResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.GetUserToEndorseResponse")
  @RequestWrapper(localName="getUserToEndorse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.GetUserToEndorse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String getUserToEndorse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="pGlobalProfileIds")
    String pGlobalProfileIds)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/searchUserToEndorse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/searchUserToEndorse", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/searchUserToEndorse/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/searchUserToEndorseResponse")
  @ResponseWrapper(localName="searchUserToEndorseResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.SearchUserToEndorseResponse")
  @RequestWrapper(localName="searchUserToEndorse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.SearchUserToEndorse")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String searchUserToEndorse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="pSearchCriteria")
    String pSearchCriteria)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(operationName="EndorseUser", action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/EndorseUser")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/EndorseUser", fault =
      { @FaultAction(value="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/EndorseUser/Fault/ServiceException",
          className=com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException.class) },
    output="http://xmlns.oracle.com/apps/hcm/hwr/coreService/WorkforceReputationService/EndorseUserResponse")
  @ResponseWrapper(localName="EndorseUserResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.EndorseUserResponse")
  @RequestWrapper(localName="EndorseUser", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.EndorseUser")
  @WebResult(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    name="result")
  public String endorseUser(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="pEndorsement")
    String pEndorsement)
    throws com.oracle.xmlns.apps.hcm.hwr.coreservice.ServiceException;

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/searchUserToEndorseAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/searchUserToEndorseAsync")
  @RequestWrapper(localName="searchUserToEndorseAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.SearchUserToEndorseAsync")
  @Oneway
  public void searchUserToEndorseAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="pSearchCriteria")
    String pSearchCriteria);

  @WebMethod(operationName="EndorseUserAsync", action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/EndorseUserAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/EndorseUserAsync")
  @RequestWrapper(localName="EndorseUserAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.EndorseUserAsync")
  @Oneway
  public void endorseUserAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="pEndorsement")
    String pEndorsement);

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserToEndorseAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getUserToEndorseAsync")
  @RequestWrapper(localName="getUserToEndorseAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.GetUserToEndorseAsync")
  @Oneway
  public void getUserToEndorseAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="pGlobalProfileIds")
    String pGlobalProfileIds);

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getMyEndorsementsAsync")
  @Action(input="http://xmlns.oracle.com/apps/hcm/hwr/coreService/getMyEndorsementsAsync")
  @RequestWrapper(localName="getMyEndorsementsAsync", targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
    className="com.oracle.xmlns.apps.hcm.hwr.coreservice.types.GetMyEndorsementsAsync")
  @Oneway
  public void getMyEndorsementsAsync(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/hwr/coreService/types/",
      name="pGlobalProfileId")
    String pGlobalProfileId);
}
